name: Publish
on:
  push:
    tags:
      - "*.*.*"

jobs:
  Publish:
    if: github.repository == 'dbrennand/virustotal-python' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-0

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1

      - name: Configure Poetry
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"

      - name: Publish virustotal-python
        run: poetry publish --build
